"""modifies entry miles constraint

Revision ID: 705602de04fb
Revises: c8665401cae8
Create Date: 2024-07-23 16:39:27.978411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705602de04fb'
down_revision = 'c8665401cae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('miles',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('miles',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
