"""creates trips

Revision ID: b7b8b5220cf9
Revises: 1471139557b3
Create Date: 2024-07-23 16:10:35.040929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b8b5220cf9'
down_revision = '1471139557b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('total_miles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
